"""Allow duplicate usernames

Revision ID: 330478b616fc
Revises: 49936bde13b2
Create Date: 2026-08-17 03:12:34.183678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330478b616fc'
down_revision = '49936bde13b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_visitor_id'), ['visitor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_visitor_id'))
        batch_op.drop_index(batch_op.f('ix_visitor_user_id'))

    # ### end Alembic commands ###
