"""Add product cost and sale prices

Revision ID: 44e1b82b3459
Revises: bfb66cb3eaae
Create Date: 2026-08-11 04:40:36.534654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e1b82b3459'
down_revision = 'bfb66cb3eaae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sale_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('sale_price')
        batch_op.drop_column('cost_price')

    # ### end Alembic commands ###
