"""Update visitor table

Revision ID: 49936bde13b2
Revises: 506b686262ee
Create Date: 2026-08-15 18:08:28.768446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49936bde13b2'
down_revision = '506b686262ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.alter_column('visitor_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('visitor_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('started_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('last_activity',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.alter_column('last_activity',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('started_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('visitor_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('visitor_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
