"""Add profile image

Revision ID: 765b6d95c613
Revises: 
Create Date: 2026-07-22 16:47:30.686398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765b6d95c613'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
