"""add visitor table

Revision ID: b7244cbd7e25
Revises: 5c7558cf60b6
Create Date: 2026-08-04 18:35:01.553300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7244cbd7e25'
down_revision = '5c7558cf60b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('page', sa.String(length=255), nullable=True),
    sa.Column('visited_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitor')
    # ### end Alembic commands ###
