"""Add product cost and sale prices

Revision ID: bfc4bb41a00e
Revises: fcd6a34cbb6e
Create Date: 2026-08-13 21:54:04.295933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc4bb41a00e'
down_revision = 'fcd6a34cbb6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('sale_start_date')
        batch_op.drop_column('sale_end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_end_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('sale_start_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
