"""Add customization to cart

Revision ID: f288292790c0

Revises: e14125650e29

Create Date: 2026-08-30 11:42:12.541745
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f288292790c0'
down_revision = 'e14125650e29'
branch_labels = None
depends_on = None


def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table(
        'cart',
        schema=None
    ) as batch_op:

        batch_op.add_column(
            sa.Column(
                'customization',
                sa.Text(),
                nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade():

    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table(
        'cart',
        schema=None
    ) as batch_op:

        batch_op.drop_column(
            'customization'
        )

    # ### end Alembic commands ###